package com.example.ui.theme

import androidx.compose.material3.darkColorScheme
import androidx.compose.material3.lightColorScheme

internal val LightColorSchemeBrown = lightColorScheme(
    primary = primaryLightYellow,
    onPrimary = onPrimaryLightYellow,
    primaryContainer = primaryContainerLightYellow,
    onPrimaryContainer = onPrimaryContainerLightYellow,
    secondary = secondaryLightYellow,
    onSecondary = onSecondaryLightYellow,
    secondaryContainer = secondaryContainerLightYellow,
    onSecondaryContainer = onSecondaryContainerLightYellow,
    tertiary = tertiaryLightYellow,
    onTertiary = onTertiaryLightYellow,
    tertiaryContainer = tertiaryContainerLightYellow,
    onTertiaryContainer = onTertiaryContainerLightYellow,
    error = errorLight,
    onError = onErrorLight,
    errorContainer = errorContainerLight,
    onErrorContainer = onErrorContainerLight,
    background = backgroundLight,
    onBackground = onBackgroundLight,
    surface = surfaceLight,
    onSurface = onSurfaceLight,
    surfaceVariant = surfaceVariantLight,
    onSurfaceVariant = onSurfaceVariantLight,
    outline = outlineLight,
    outlineVariant = outlineVariantLight,
    scrim = scrimLight,
    inverseSurface = inverseSurfaceLight,
    inverseOnSurface = inverseOnSurfaceLight,
    inversePrimary = inversePrimaryLight,
    surfaceDim = surfaceDimLight,
    surfaceBright = surfaceBrightLight,
    surfaceContainerLowest = surfaceContainerLowestLight,
    surfaceContainerLow = surfaceContainerLowLight,
    surfaceContainer = surfaceContainerLight,
    surfaceContainerHigh = surfaceContainerHighLight,
    surfaceContainerHighest = surfaceContainerHighestLight,
)

internal val DarkColorSchemeBrown = darkColorScheme(
    primary = primaryDarkYellow,
    onPrimary = onPrimaryDarkYellow,
    primaryContainer = primaryContainerDarkYellow,
    onPrimaryContainer = onPrimaryContainerDarkYellow,
    secondary = secondaryDarkYellow,
    onSecondary = onSecondaryDarkYellow,
    secondaryContainer = secondaryContainerDarkYellow,
    onSecondaryContainer = onSecondaryContainerDarkYellow,
    tertiary = tertiaryDarkYellow,
    onTertiary = onTertiaryDarkYellow,
    tertiaryContainer = tertiaryContainerDarkYellow,
    onTertiaryContainer = onTertiaryContainerDarkYellow,
    error = errorDark,
    onError = onErrorDark,
    errorContainer = errorContainerDark,
    onErrorContainer = onErrorContainerDark,
    background = backgroundDark,
    onBackground = onBackgroundDark,
    surface = surfaceDark,
    onSurface = onSurfaceDark,
    surfaceVariant = surfaceVariantDark,
    onSurfaceVariant = onSurfaceVariantDark,
    outline = outlineDark,
    outlineVariant = outlineVariantDark,
    scrim = scrimDark,
    inverseSurface = inverseSurfaceDark,
    inverseOnSurface = inverseOnSurfaceDark,
    inversePrimary = inversePrimaryDark,
    surfaceDim = surfaceDimDark,
    surfaceBright = surfaceBrightDark,
    surfaceContainerLowest = surfaceContainerLowestDark,
    surfaceContainerLow = surfaceContainerLowDark,
    surfaceContainer = surfaceContainerDark,
    surfaceContainerHigh = surfaceContainerHighDark,
    surfaceContainerHighest = surfaceContainerHighestDark,
)