package com.example.ui.theme

import androidx.compose.ui.graphics.Color

val otpLightGray = Color(0xff262626)
val otpGray = Color(0xff1c1c1c)

val errorLight = Color(0xFFBA1A1A)
val onErrorLight = Color(0xFFFFFFFF)
val errorContainerLight = Color(0xFFFFDAD6)
val onErrorContainerLight = Color(0xFF93000A)
val backgroundLight = Color(0xFFF5FAFB)
val onBackgroundLight = Color(0xFF171D1E)
val surfaceLightGreen = Color(0xFF2AE881)
val onSurfaceLight = Color(0xFF171D1E)
val surfaceVariantLight = Color(0xFFDBE4E6)
val onSurfaceVariantLight = Color(0xFF3F484A)
val outlineLight = Color(0xFF6F797A)
val outlineVariantLight = Color(0xFFBFC8CA)
val scrimLight = Color(0xFF000000)
val inverseSurfaceLight = Color(0xFF2B3133)
val inverseOnSurfaceLight = Color(0xFFECF2F3)
val inversePrimaryLight = Color(0xFF82D3E0)
val surfaceDimLight = Color(0xFFD5DBDC)
val surfaceBrightLight = Color(0xFFF5FAFB)
val surfaceContainerLowestLight = Color(0xFFFFFFFF)
val surfaceContainerLowLight = Color(0xFFEFF5F6)
val surfaceContainerLight = Color(0xFFE9EFF0)
val surfaceContainerHighLight = Color(0xFFE3E9EA)
val surfaceContainerHighestLight = Color(0xFFDEE3E5)

val errorDark = Color(0xFFFFB4AB)
val onErrorDark = Color(0xFF690005)
val errorContainerDark = Color(0xFF93000A)
val onErrorContainerDark = Color(0xFFFFDAD6)
val backgroundDark = Color(0xFF0E1415)
val onBackgroundDark = Color(0xFFFFFFFF)
val surfaceDark = Color(0xFF0E1415)
val onSurfaceDark = Color(0xFFFFFFFF)
val surfaceVariantDark = Color(0xFF3F484A)
val onSurfaceVariantDark = Color(0xFFBFC8CA)
val outlineDark = Color(0xFF899294)
val outlineVariantDark = Color(0xFF3F484A)
val scrimDark = Color(0xFF000000)
val inverseSurfaceDark = Color(0xFFDEE3E5)
val inverseOnSurfaceDark = Color(0xFF2B3133)
val inversePrimaryDark = Color(0xFF006874)
val surfaceDimDark = Color(0xFF0E1415)
val surfaceBrightDark = Color(0xFF343A3B)
val surfaceContainerLowestDark = Color(0xFF090F10)
val surfaceContainerLowDark = Color(0xFF171D1E)
val surfaceContainerDark = Color(0xFF1B2122)
val surfaceContainerHighDark = Color(0xFF252B2C)
val surfaceContainerHighestDark = Color(0xFF303637)

val primaryLightGreen = Color(0xFF2AE881)
val onPrimaryLightGreen = Color(0xFFFFFFFF)
val primaryContainerLightGreen = Color(0xFFD4FAE6)
val onPrimaryContainerLightGreen = Color(0xFF004F58)
val secondaryLightGreen = Color(0xFF4A6267)
val onSecondaryLightGreen = Color(0xFFFFFFFF)
val secondaryContainerLightGreen = Color(0xFFD4FAE6)
val onSecondaryContainerLightGreen = Color(0xFF334B4F)
val tertiaryLightGreen = Color(0xFFD4FAE6)
val onTertiaryLightGreen = Color(0xFFFFFFFF)
val tertiaryContainerLightGreen = Color(0xFFDAE2FF)
val onTertiaryContainerLightGreen = Color(0xFF3B4664)

val primaryDarkGreen = Color(0xFF98D5A4)
val onPrimaryDarkGreen = Color(0xFF00391A)
val primaryContainerDarkGreen = Color(0xFF15512C)
val onPrimaryContainerDarkGreen = Color(0xFFB3F1BF)
val secondaryDarkGreen = Color(0xFFB7CCB8)
val onSecondaryDarkGreen = Color(0xFF223526)
val secondaryContainerDarkGreen = Color(0xFF384B3C)
val onSecondaryContainerDarkGreen = Color(0xFFD2E8D3)
val tertiaryDarkGreen = Color(0xFFA2CED9)
val onTertiaryDarkGreen = Color(0xFF01363F)
val tertiaryContainerDarkGreen = Color(0xFF204D56)
val onTertiaryContainerDarkGreen = Color(0xFFBEEAF5)


val primaryLightBlue = Color(0xFF206487)
val onPrimaryLightBlue = Color(0xFFFFFFFF)
val primaryContainerLightBlue = Color(0xFFC6E7FF)
val onPrimaryContainerLightBlue = Color(0xFF004C6B)
val secondaryLightBlue = Color(0xFF4F616D)
val onSecondaryLightBlue = Color(0xFFFFFFFF)
val secondaryContainerLightBlue = Color(0xFFD2E5F4)
val onSecondaryContainerLightBlue = Color(0xFF374955)
val tertiaryLightBlue = Color(0xFF62597C)
val onTertiaryLightBlue = Color(0xFFFFFFFF)
val tertiaryContainerLightBlue = Color(0xFFE7DEFF)
val onTertiaryContainerLightBlue = Color(0xFF4A4263)
val surfaceLight = Color(0xFFF5FAFB)

val primaryDarkBlue = Color(0xFF91CEF5)
val onPrimaryDarkBlue = Color(0xFF00344B)
val primaryContainerDarkBlue = Color(0xFF004C6B)
val onPrimaryContainerDarkBlue = Color(0xFFC6E7FF)
val secondaryDarkBlue = Color(0xFFB6C9D8)
val onSecondaryDarkBlue = Color(0xFF20333E)
val secondaryContainerDarkBlue = Color(0xFF374955)
val onSecondaryContainerDarkBlue = Color(0xFFD2E5F4)
val tertiaryDarkBlue = Color(0xFFCCC1E9)
val onTertiaryDarkBlue = Color(0xFF332C4C)
val tertiaryContainerDarkBlue = Color(0xFF4A4263)
val onTertiaryContainerDarkBlue = Color(0xFFE7DEFF)

val primaryLightYellow = Color(0xFF7C580D)
val onPrimaryLightYellow = Color(0xFFFFFFFF)
val primaryContainerLightYellow = Color(0xFFFFDEAB)
val onPrimaryContainerLightYellow = Color(0xFF5F4100)
val secondaryLightYellow = Color(0xFF6D5C3F)
val onSecondaryLightYellow = Color(0xFFFFFFFF)
val secondaryContainerLightYellow = Color(0xFFF8DFBB)
val onSecondaryContainerLightYellow = Color(0xFF54442A)
val tertiaryLightYellow = Color(0xFF4E6543)
val onTertiaryLightYellow = Color(0xFFFFFFFF)
val tertiaryContainerLightYellow = Color(0xFFD0EBC0)
val onTertiaryContainerLightYellow = Color(0xFF374D2D)

val primaryDarkYellow = Color(0xFFEFBF6D)
val onPrimaryDarkYellow = Color(0xFF422C00)
val primaryContainerDarkYellow = Color(0xFF5F4100)
val onPrimaryContainerDarkYellow = Color(0xFFFFDEAB)
val secondaryDarkYellow = Color(0xFFDBC3A1)
val onSecondaryDarkYellow = Color(0xFF3C2E16)
val secondaryContainerDarkYellow = Color(0xFF54442A)
val onSecondaryContainerDarkYellow = Color(0xFFF8DFBB)
val tertiaryDarkYellow = Color(0xFFB4CEA5)
val onTertiaryDarkYellow = Color(0xFF213618)
val tertiaryContainerDarkYellow = Color(0xFF374D2D)
val onTertiaryContainerDarkYellow = Color(0xFFD0EBC0)