name: PR Checks

on:
  pull_request:
    branches: [ "main" ]
    paths-ignore:
      - '**.md'

env:
  gradleFlags: --parallel --stacktrace --no-configuration-cache --no-daemon

jobs:
  build-app:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Setup environment
        uses: ./.github/actions/init-gradle
      - name: Build
        run: ./gradlew :app:assembleDebug $gradleFlags
      - name: Generate build time report
        uses: ./.github/actions/build-time-report
        with:
          file: app/build/reports/buildTimeTracker/build.csv
          output-file: buildTime.csv
      - name: Upload apk
        uses: actions/upload-artifact@v4
        with:
          name: app.apk
          path: app/build/outputs/apk/debug/app-debug.apk
      - name: Upload time report
        uses: actions/upload-artifact@v4
        with:
          name: buildTime.csv
          path: buildTime.csv

  run-detekt:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Setup environment
        uses: ./.github/actions/init-gradle
      - name: Run Detekt
        run: ./gradlew detekt $gradleFlags
      - name: Generate Markdown report
        run: cat build/reports/detekt/detekt.md > $GITHUB_STEP_SUMMARY
      - name: Upload SARIF
        uses: github/codeql-action/upload-sarif@v3
        if: success() || failure()
        with:
          sarif_file: build/reports/detekt/detekt.sarif
      - name: Upload report
        uses: actions/upload-artifact@v4
        with:
          name: detekt.html
          path: build/reports/detekt/detekt.html

  check-app-size:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Setup environment
        uses: ./.github/actions/init-gradle
      - name: Analyze size
        run: ./gradlew :app:analyzeDebugBundle $gradleFlags
      - name: Upload report
        uses: actions/upload-artifact@v4
        with:
          name: ruler-report.html
          path: app/build/reports/ruler/debug/report.html

  check-module-graph:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Setup environment
        uses: ./.github/actions/init-gradle
      - name: Check Graph
        run: ./gradlew :app:assertModuleGraph $gradleFlags
      - name: Generate graph
        run: ./gradlew :app:generateModulesGraphvizText -Pmodules.graph.output.gv=all_modules $gradleFlags
      - name: Generate Markdown report
        run: |
          set -e
          echo '```' > $GITHUB_STEP_SUMMARY
          cat all_modules >> $GITHUB_STEP_SUMMARY
          echo "" >> $GITHUB_STEP_SUMMARY
          echo '```' >> $GITHUB_STEP_SUMMARY
      - name: Draw graph
        uses: ./.github/actions/draw-graph
        with:
          input-file: all_modules
          output-file: all_modules.png
      - name: Upload report
        uses: actions/upload-artifact@v4
        with:
          name: all_modules.png
          path: all_modules.png
